server:
  port: 8082

spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password: admin
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    connection-timeout: 10000
    requested-heartbeat: 10

app:
  rabbitmq:
    queue: PAYMENT_RECONCILE_QUEUE
    queue-retry: PAYMENT_RECONCILE_QUEUE_RETRY
    exchange: PAYMENT_EXCHANGE
    max-retry: 3
    time-to-live: 10000
  redis:
    time-to-live: 10



